config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/recommender-system:
      branch: main
      repo: https://github.com/cyfronet-fid/recommender-system
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/recommender-system git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-asparagus-meerkat.sh
        container: qc.acc_bumpy-wisteria-spoonbill
  QC.Doc:
    repos:
      github.com/cyfronet-fid/recommender-system find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-lemon-raccoon.sh
        container: qc.doc_scaly-aqua-leopard
      github.com/cyfronet-fid/recommender-system git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-coral-baboon.sh
        container: qc.doc_stinky-taupe-spider
      github.com/cyfronet-fid/recommender-system markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-burgundy-olm.sh
        container: qc.doc_jumpy-persimmon-mule
  QC.Lic:
    repos:
      github.com/cyfronet-fid/recommender-system licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-orchid-slug.sh
        container: qc.lic_pretty-copper-hamster
  QC.Sec:
    repos:
      github.com/cyfronet-fid/recommender-system bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-maroon-kudu.sh
        container: qc.sec_shaggy-rose-cheetah
  QC.Sty:
    repos:
      github.com/cyfronet-fid/recommender-system flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-amaranth-flamingo.sh
        container: qc.sty_queasy-pink-okapi
      github.com/cyfronet-fid/recommender-system hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-seashell-spitz.sh
        container: qc.sty_leaky-dandelion-tamarin
      github.com/cyfronet-fid/recommender-system jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-alizarin-vulture.sh
        container: qc.sty_randy-white-angelfish
  QC.Ver:
    repos:
      github.com/cyfronet-fid/recommender-system get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-aquamarine-spoonbill.sh
        container: qc.ver_breezy-wisteria-shrimp
timeout: 5400
